[build]
  publish = "./"
  command = "npm run build"

[[redirects]]
    from = "/osa/*"
    to = "https://hkuesd.hku.hk:8000/osa/:splat"
    status = 200
    force = true
    headers = {Referer = "https://hkuesd.hku.hk:8000"}


[[redirects]]
    from = "/ihp/*"
    to = "https://bs.cse.hku.hk/ihpbooking/:splat"
    status = 200
    force = true
    headers = {Referer = "https://bs.cse.hku.hk"}